version: '3.8'

services:
  books-db:
    image: mysql:8.0
    container_name: books-db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - books_data:/var/lib/mysql

volumes:
  books_data: